-- Script para insertar proveedores de pago predefinidos
-- Ejecutar después de la migración de la base de datos

INSERT INTO proveedores_pago (
    id,
    nombre,
    codigo,
    tipo,
    descripcion,
    "logoUrl",
    "sitioWeb",
    "apiBaseUrl",
    "versionApi",
    "documentacionUrl",
    "soportaWebhooks",
    "soportaTarjetas",
    "soportaTransferencias",
    "soportaEfectivo",
    "soportaRecurrentes",
    "montoMinimo",
    "montoMaximo",
    "comisionPorcentaje",
    "comisionFija",
    "tiempoExpiracionMinutos",
    "tiempoConfirmacionHoras",
    "paisesDisponibles",
    "monedasSoportadas",
    estado,
    activo,
    "createdAt",
    "updatedAt"
) VALUES
-- MercadoPago
(
    gen_random_uuid(),
    'MercadoPago',
    'mercadopago',
    'MERCADOPAGO',
    'Plataforma de pagos online de Mercado Libre',
    'https://http2.mlstatic.com/frontend-assets/ui-navigation/5.18.5/mercadopago/logo__large_plus.png',
    'https://www.mercadopago.com.ar',
    'https://api.mercadopago.com',
    'v1',
    'https://www.mercadopago.com.ar/developers',
    true,
    true,
    true,
    true,
    true,
    1.00,
    9999999.00,
    2.99,
    0.00,
    60,
    72,
    ARRAY['AR', 'BR', 'CL', 'CO', 'MX', 'PE', 'UY'],
    ARRAY['ARS', 'BRL', 'CLP', 'COP', 'MXN', 'PEN', 'UYU'],
    'ACTIVO',
    true,
    NOW(),
    NOW()
),
-- Stripe
(
    gen_random_uuid(),
    'Stripe',
    'stripe',
    'STRIPE',
    'Plataforma global de procesamiento de pagos',
    'https://images.ctfassets.net/fzn2n1nzq965/3AGidihOJl4nH9D1vDjM60/4c24e61ab5a4f09e3263f6b4e7ce9d37/Stripe_icon_-_square.png',
    'https://stripe.com',
    'https://api.stripe.com',
    '2020-08-27',
    'https://stripe.com/docs',
    true,
    true,
    true,
    false,
    true,
    0.50,
    999999.00,
    2.90,
    0.30,
    60,
    168,
    ARRAY['US', 'AR', 'BR', 'MX', 'ES', 'FR', 'IT', 'DE', 'GB'],
    ARRAY['USD', 'ARS', 'BRL', 'MXN', 'EUR', 'GBP'],
    'ACTIVO',
    true,
    NOW(),
    NOW()
),
-- PayPal
(
    gen_random_uuid(),
    'PayPal',
    'paypal',
    'PAYPAL',
    'Servicio de pagos en línea que permite transferir dinero',
    'https://www.paypalobjects.com/webstatic/mktg/Logo/pp-logo-200px.png',
    'https://www.paypal.com',
    'https://api-m.paypal.com',
    'v2',
    'https://developer.paypal.com/docs',
    true,
    true,
    true,
    false,
    true,
    2.00,
    10000.00,
    3.49,
    0.00,
    180,
    72,
    ARRAY['US', 'AR', 'BR', 'MX', 'ES', 'FR', 'IT', 'DE', 'GB', 'CA'],
    ARRAY['USD', 'ARS', 'BRL', 'MXN', 'EUR', 'GBP', 'CAD'],
    'ACTIVO',
    true,
    NOW(),
    NOW()
),
-- Decidir (First Data)
(
    gen_random_uuid(),
    'Decidir',
    'decidir',
    'DECIDIR',
    'Plataforma de pagos de Prisma Medios de Pago',
    'https://decidir.com.ar/assets/img/logo-decidir.png',
    'https://decidir.com.ar',
    'https://live.decidir.com/api',
    'v1',
    'https://decidir.com.ar/desarrolladores',
    true,
    true,
    false,
    false,
    false,
    10.00,
    999999.00,
    2.50,
    0.00,
    30,
    72,
    ARRAY['AR'],
    ARRAY['ARS'],
    'ACTIVO',
    true,
    NOW(),
    NOW()
),
-- Todo Pago
(
    gen_random_uuid(),
    'TodoPago',
    'todopago',
    'TODO_PAGO',
    'Plataforma de pagos del Banco de la Provincia de Buenos Aires',
    'https://todopago.com.ar/sites/TodoPago/img/tp_logo.png',
    'https://todopago.com.ar',
    'https://developers.todopago.com.ar/api',
    'v2',
    'https://developers.todopago.com.ar',
    true,
    true,
    false,
    true,
    false,
    1.00,
    999999.00,
    2.75,
    0.00,
    60,
    72,
    ARRAY['AR'],
    ARRAY['ARS'],
    'ACTIVO',
    true,
    NOW(),
    NOW()
),
-- Rapipago
(
    gen_random_uuid(),
    'Rapipago',
    'rapipago',
    'RAPIPAGO',
    'Red de cobranza y pagos con más de 7000 sucursales',
    'https://www.rapipago.com.ar/web/assets/img/logo-rapipago.png',
    'https://www.rapipago.com.ar',
    'https://www.rapipago.com.ar/api',
    'v1',
    'https://www.rapipago.com.ar/desarrolladores',
    false,
    false,
    false,
    true,
    false,
    10.00,
    99999.00,
    1.50,
    5.00,
    1440,
    72,
    ARRAY['AR'],
    ARRAY['ARS'],
    'ACTIVO',
    true,
    NOW(),
    NOW()
),
-- Pago Fácil
(
    gen_random_uuid(),
    'PagoFácil',
    'pagofacil',
    'PAGO_FACIL',
    'Red de pagos con presencia nacional',
    'https://www.pagofacil.com.ar/assets/img/logo.png',
    'https://www.pagofacil.com.ar',
    'https://www.pagofacil.com.ar/api',
    'v1',
    'https://www.pagofacil.com.ar/desarrolladores',
    false,
    false,
    false,
    true,
    false,
    5.00,
    50000.00,
    1.25,
    3.00,
    2880,
    72,
    ARRAY['AR'],
    ARRAY['ARS'],
    'ACTIVO',
    true,
    NOW(),
    NOW()
),
-- Transferencia Directa
(
    gen_random_uuid(),
    'Transferencia Directa',
    'transferencia_directa',
    'TRANSFERENCIA_DIRECTA',
    'Pagos mediante transferencia bancaria directa',
    null,
    null,
    null,
    null,
    null,
    false,
    false,
    true,
    false,
    false,
    1.00,
    null,
    0.00,
    0.00,
    4320,
    168,
    ARRAY['AR'],
    ARRAY['ARS'],
    'ACTIVO',
    true,
    NOW(),
    NOW()
);

-- Insertar configuraciones predeterminadas para administrar
COMMENT ON TABLE proveedores_pago IS 'Catálogo de proveedores de pago disponibles en el sistema';
COMMENT ON TABLE proveedores_pago_cooperativas IS 'Configuración específica de proveedores de pago por cooperativa';

-- Índices adicionales para optimizar consultas
CREATE INDEX IF NOT EXISTS idx_proveedores_pago_tipo_activo ON proveedores_pago(tipo, activo);
CREATE INDEX IF NOT EXISTS idx_proveedores_pago_estado ON proveedores_pago(estado);
CREATE INDEX IF NOT EXISTS idx_proveedores_pago_cooperativas_activo ON proveedores_pago_cooperativas(activo);
CREATE INDEX IF NOT EXISTS idx_proveedores_pago_cooperativas_principal ON proveedores_pago_cooperativas(esPrincipal) WHERE esPrincipal = true;